### ISSUE TITLE
placeholder overlapping label when using floating labels on chrome

### ISSUE THREAD

**Issue by kxc0re** [coreui/coreui#371]
On Chrome Floating Labels overlap the Placeholders set for the FormInputs

![image](https://user-images.githubusercontent.com/9086904/158159408-da3d4c45-556f-4ae1-b76a-3186dfce7bf0.png)

[codepen.io/kxc0re/pen/abEzBRa](https://codepen.io/kxc0re/pen/abEzBRa)

OS: Windows 10
Browser: Chrome v99.0.4844.51

related:
https://github.com/twbs/bootstrap/issues/32800

potential fix:
hiding the placeholder on unfocused form-inputs with shown placeholder:
```css
.form-floating > .form-control:placeholder-shown:not(:focus)::placeholder {
  color: transparent;
  text-shadow: none;
}
```
or a specific version for chrome-based browsers `::-webkit-input-placeholder`
firefox doesn't seem to have that issue since its not showing the placeholder at all, which i would also consider a bug
